//
// Created by Sharon Nikritin on 2022-11-18.
//

#include "Admin.hpp"

Admin::Admin(std::string userName, std::string password) {
    this ->userName = userName;
    this -> password = password;
}

Admin::~Admin() {

}

std::string Admin::getPassword() {
    return password;
}

std::string Admin::getUserName() {
    return userName;
}

bool Admin::authenticateAdmin(std::string userName, std::string password) {

}

std::string Admin::tableName() const {
    return "Admin";
}

std::vector<std::string> Admin ::columns() const {
    return {"userName", "password"};
}

std::set<std::string> Admin::keys() const {
    return {columns()[0]};
}

bool Admin::isAutoGeneratedKey() const {
    return false;
}

std::map<std::string, std::any> Admin ::toMap() const {
    std::map<std::string, std::any> mMap;
    mMap[columns()[0]] = userName;
    mMap[columns()[1]] = password;

    return mMap;
}

Model * Admin::fromMap(std::map<std::string, std::any> mMap) const{
    std::string mUserName = std::any_cast<std::string>(mMap[columns()[0]]);
    std::string mPassword = std::any_cast<std::string>(mMap[columns()[1]]);

    Admin *model = new Admin (mUserName, mPassword);
    return model;
}
