//
// Created by Sharon Nikritin on 2022-11-18.
//

#ifndef Admin_hpp
#define Admin_hpp

#include <map>
#include <string>

#include "Model.hpp"


class Admin : public Model{
public:
    Admin(std::string userName="", std::string password="");

    ~Admin();

    std::string getUserName();

    std::string getPassword();

    bool authenticateAdmin (std::string userName, std::string password);

private:
    std::string userName;
    std::string password;

    virtual std::string tableName() const override;
    virtual std::vector<std::string> columns() const override;
    virtual std::set<std::string> keys() const override;
    virtual bool isAutoGeneratedKey() const override;
    virtual std::map<std::string, std::any> toMap() const override;
    virtual Model * fromMap(std::map<std::string, std::any> mMap) const override;

};


#endif //Admin_hpp
