//
// Created by Sharon Nikritin on 2022-11-05.
//
#include "AuthToken.h"

AuthToken ::AuthToken(std::string tokenID, time_t createdDate) {
    this -> tableName = "AuthToken";
    this -> keys = "tokenID";
    this -> autoGeneratedKey = "";

    this -> tokenID = tokenID;
    this -> createdDate = createdDate;

}

AuthToken ::~AuthToken() {

}

std::map<std::string, std::any> InventoryItem:: toMap()
{
    std::map<std::string, std::any> mMap;
    mMap["tokenID"] = tokenID;
    mMap["createdDate"] = createdDate;

    return mMap;
}

Model * InventoryItem::fromMap(std::map<std::string, std::any> mMap)
{

    std::string mID = std::any_cast<int>(mMap["tokenID"]);
    time_t mCreatedDate = std::any_cast<int>(mMap["createdDate"])
    MenuItem *model = new MenuItem(mID, mCreatedDate);

    return model;
}

std::string AuthToken::getTokenID() {
    return tokenID;
}

bool AuthToken::isValid() {
    return true;
}


