//
// Created by Sharon Nikritin on 2022-11-05.
//
#include "AuthToken.hpp"

AuthToken ::AuthToken(std::string tokenID, std::string createdDate) {
    this -> tokenID = tokenID;
    this -> createdDate = createdDate;

}

AuthToken ::~AuthToken() {

}

std::string AuthToken::getTokenID() {
    return tokenID;
}

bool AuthToken::isValid() {
    return true;
}


std::string AuthToken::tableName() const
{
    return "AuthToken";
}

std::vector<std::string> AuthToken::columns() const
{
    return { "tokenID", "createdDate" };
}

std::set<std::string> AuthToken::keys() const
{
    return { columns()[0] };
}

bool AuthToken::isAutoGeneratedKey() const
{
    return false;
}

std::map<std::string, std::any> AuthToken:: toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap[columns()[0]] = tokenID;
    mMap[columns()[1]] = createdDate;

    return mMap;
}

Model * AuthToken::fromMap(std::map<std::string, std::any> mMap) const
{

    std::string mID = std::any_cast<std::string>(mMap[columns()[0]]);
    std::string mCreatedDate = std::any_cast<std::string>(mMap[columns()[1]]);
    AuthToken *model = new AuthToken(mID, mCreatedDate);

    return model;
}
