//
// Created by Sharon Nikritin on 2022-11-07.
//


#include "InventoryItem.hpp"

InventoryItem :: InventoryItem(int itemID, std::string ItemName, int quantity)
{
    this -> tableName = "InventoryItem";
    this -> columns = { "itemID", "itemName", "quantity" };
    this -> keys = { columns[0] };
    this -> isAutoGeneratedKey = true;

    this->itemID = itemID;
    this-> itemName = ItemName;
    this-> quantity = quantity;


}

InventoryItem :: ~InventoryItem() {

}

std::map<std::string, std::any> InventoryItem:: toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap[columns[0]] = itemID;
    mMap[columns[1]] = itemName;
    mMap[columns[2]] = quantity;

    return mMap;
}

Model * InventoryItem::fromMap(std::map<std::string, std::any> mMap) const
{

    int mID = std::any_cast<int>(mMap[columns[0]]);
    std::string mName = std::any_cast<std::string>(mMap[columns[1]]);
    int mQuantity = std::any_cast<int>(mMap[columns[2]]);
    InventoryItem *model = new InventoryItem(mID, mName, mQuantity);

    return model;
}

int InventoryItem::getItemID() {
    return itemID;
}

std::string InventoryItem ::getItemName() {
    return itemName;
}

int InventoryItem ::getQuantity() {
    return quantity;
}

void InventoryItem ::setItemID(int itemID) {
    this -> itemID = itemID;
}

void InventoryItem ::setItemName(std::string itemName) {
    this -> itemName = itemName;
}

void InventoryItem ::setQuantity(int quantity) {
    this -> quantity = quantity;
}
