//
// Created by Sharon Nikritin on 2022-11-07.
//


#include "InventoryItem.h"

InventoryItem :: InventoryItem(int itemID, std::string ItemName, int quantity){
    this -> tableName = "InventoryItem";
    this -> keys = {"name"};
    this -> autoGeneratedKey = "itemID";

    this->itemID = itemID;
    this-> itemName = name;
    this-> quantity = quantity;


}

InventoryItem :: ~InventoryItem() {

}

std::map<std::string, std::any> InventoryItem:: toMap()
{
    std::map<std::string, std::any> mMap;
    mMap["itemID"] = itemID;
    mMap["itemName"] = itemName;
    mMap["quantity"] = quantity;

    return mMap;
}

Model * InventoryItem::fromMap(std::map<std::string, std::any> mMap)
{

    int mID = std::any_cast<int>(mMap["itemID"]);
    std::string mName = std::any_cast<std::string>(mMap["itemName"]);
    int mQuantity = std::any_cast<int>(mMap["quantity"])
    MenuItem *model = new MenuItem(mID, mName, mQuantity);

    return model;
}

int InventoryItem::getItemID() {
    return itemID;
}

std::string InventoryItem ::getItemName() {
    return itemName;
}

int InventoryItem ::getQuantity() {
    return quantity;
}

void InventoryItem ::setItemID(int itemID) {
    this -> itemID = itemID;
}

void InventoryItem ::setItemName(std::string itemName) {
    this -> itemName = itemName;
}

void InventoryItem ::setQuantity(int quantity) {
    this -> quantity = quantity;
}
