
#include "InventoryItem.hpp"

InventoryItem :: InventoryItem(int itemID, std::string ItemName, int quantity)
{
    this->itemID = itemID;
    this-> itemName = ItemName;
    this-> quantity = quantity;
}

InventoryItem :: ~InventoryItem() {

}

int InventoryItem::getItemID() {
    return itemID;
}

std::string InventoryItem ::getItemName() {
    return itemName;
}

int InventoryItem ::getQuantity() {
    return quantity;
}

void InventoryItem ::setItemID(int itemID) {
    this -> itemID = itemID;
}

void InventoryItem ::setItemName(std::string itemName) {
    this -> itemName = itemName;
}

void InventoryItem ::setQuantity(int quantity) {
    this -> quantity = quantity;
}


std::string InventoryItem::tableName() const
{
    return "InventoryItem";
}

std::vector<std::string> InventoryItem::columns() const
{
    return { "itemID", "itemName", "quantity" };
}

std::set<std::string> InventoryItem::keys() const
{
    return { columns()[0] };
}

bool InventoryItem::isAutoGeneratedKey() const
{
    return true;
}

std::map<std::string, std::any> InventoryItem:: toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap[columns()[0]] = itemID;
    mMap[columns()[1]] = itemName;
    mMap[columns()[2]] = quantity;

    return mMap;
}

Model * InventoryItem::fromMap(std::map<std::string, std::any> mMap) const
{

    int mID = std::any_cast<int>(mMap[columns()[0]]);
    std::string mName = std::any_cast<std::string>(mMap[columns()[1]]);
    int mQuantity = std::any_cast<int>(mMap[columns()[2]]);
    InventoryItem *model = new InventoryItem(mID, mName, mQuantity);

    return model;
}
