//
// Created by Sharon Nikritin on 2022-11-07.
//

#ifndef InventoryItem_hpp
#define InventoryItem_hpp

#include <string>
#include <map>

#include "Model.hpp"

class InventoryItem: public Model
{
public:
    InventoryItem(int itemID = 0, std::string itemName = "", int quantity = 0);

    ~InventoryItem();

    int getItemID();

    std::string getItemName();

    int getQuantity();

    void setItemID(int itemID);

    void setItemName (std::string itemName);

    void setQuantity (int quantity);

private:
    int itemID;
    std::string itemName;
    int quantity;

    virtual std::string tableName() const override;
    virtual std::vector<std::string> columns() const override;
    virtual std::set<std::string> keys() const override;
    virtual bool isAutoGeneratedKey() const override;
    virtual std::map<std::string, std::any> toMap() const override;
    virtual Model * fromMap(std::map<std::string, std::any> mMap) const override;
};


#endif //InventoryItem.hpp

