//
// Created by Sharon Nikritin on 2022-11-07.
//

#include "MenuItemIngredient.hpp"

MenuItemIngredient ::MenuItemIngredient(std::string menuItemName, int inventoryItemID, int quantity) {
    this -> tableName = "MenuItemIngredient";
    this -> keys = { "menuItemName" };
    this -> autoGeneratedKey = "";

    this -> menuItemName = menuItemName;
    this -> inventoryItemID = inventoryItemID;
    this -> quantity = quantity;

}

MenuItemIngredient :: ~MenuItemIngredient() {

}

std::map<std::string, std::any> MenuItemIngredient:: toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap["menuItemName"] = menuItemName;
    mMap["inventoryItemID"] = inventoryItemID;
    mMap["quantity"] = quantity;

    return mMap;
}

Model * MenuItemIngredient::fromMap(std::map<std::string, std::any> mMap) const
{

    std::string mName = std::any_cast<std::string>(mMap["menuItemName"]);
    int mID = std::any_cast<int>(mMap["inventoryItemID"]);
    int mQuantity = std::any_cast<int>(mMap["quantity"]);
    MenuItemIngredient *model = new MenuItemIngredient(mName, mID, mQuantity);

    return model;
}

std::string MenuItemIngredient ::getMenuItemName() {
    return menuItemName;
}

int MenuItemIngredient ::getInventoryItemID() {
    return inventoryItemID;
}

int MenuItemIngredient ::getQuantity() {
    return quantity;
}

void MenuItemIngredient ::setMenuItemName(std::string menuItemName) {
    this -> menuItemName = menuItemName;
}

void MenuItemIngredient ::setInventoryItemID(int inventoryItemID) {
    this -> inventoryItemID = inventoryItemID;
}

void MenuItemIngredient ::setQuantity(int quantity) {
    this -> quantity = quantity;
}
