//
// Created by Sharon Nikritin on 2022-11-07.
//

#ifndef menuItemIngredient_hpp
#define menuItemIngredient_hpp

#include <string>
#include <map>

#include "Model.hpp"

class MenuItemIngredient : public Model
{
public:
    MenuItemIngredient(std::string menuItemName = "", int inventoryItemID = 0, int quantity = 0);

    ~MenuItemIngredient();

    std::string getMenuItemName();

    int getInventoryItemID();

    int getQuantity();

    void setMenuItemName(std::string menuItemName);

    void setInventoryItemID (int inventoryItemID);

    void setQuantity (int quantity);

private:
    std::string menuItemName;
    int inventoryItemID;
    int quantity;

    virtual std::string tableName() const override;
    virtual std::vector<std::string> columns() const override;
    virtual std::set<std::string> keys() const override;
    virtual bool isAutoGeneratedKey() const override;
    virtual std::map<std::string, std::any> toMap() const override;
    virtual Model * fromMap(std::map<std::string, std::any> mMap) const override;
};


#endif //menuItemIngredient_hpp

