//
//  MenuItem.cpp
//
//  Created by Julian Koksal on 2022-09-25.
//

#include "MenuItem.hpp"

MenuItem::MenuItem(std::string name, double price, std::string description)
{
    this->name = name;
    this->price = price;
    this->description = description;
}

MenuItem::~MenuItem()
{
    
}

std::string MenuItem::getName()
{
    return name;
}

double MenuItem::getPrice()
{
    return price;
}

std::string MenuItem::getDescription()
{
    return description;
}


void MenuItem::setPrice(double price) {
    this->price = price;
}

void MenuItem::setDescription(std::string description)
{
    this->description = description;
}


std::string MenuItem::tableName() const
{
    return "MenuItem";
}

std::vector<std::string> MenuItem::columns() const
{
    return { "name", "price", "description" };
}

std::set<std::string> MenuItem::keys() const
{
    return { columns()[0] };
}

bool MenuItem::isAutoGeneratedKey() const
{
    return false;
}

std::map<std::string, std::any> MenuItem::toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap[columns()[0]] = name;
    mMap[columns()[1]] = price;
    mMap[columns()[2]] = description;
    
    return mMap;
}

Model * MenuItem::fromMap(std::map<std::string, std::any> mMap) const
{
    std::string mName = std::any_cast<std::string>(mMap[columns()[0]]);
    double mPrice = std::any_cast<double>(mMap[columns()[1]]);
    std::string mDescription = std::any_cast<std::string>(mMap[columns()[2]]);
    
    MenuItem *model = new MenuItem(mName, mPrice, mDescription);
    return model;
}
