//
//  Model.hpp
//

#ifndef Model_hpp
#define Model_hpp

#include <string>
#include <any>
#include <set>
#include <map>
#include <vector>

/**
 * Abstract class representing a row of a database table.
 * @author Julian Koksal
 * @date 2022-09-25
 */
class Model
{
    friend class DBHelper;
private:
    static int foo;
    /**
     * @brief The name of the SQL table that this model represents.
     * @return the table name
     */
    virtual std::string tableName() const = 0;
    
    /**
     * @brief Returns the columns of the SQL table, in the correct order.
     * @return vector of column names
     */
    virtual std::vector<std::string> columns() const = 0;
    
    /**
     * @brief Return the primary key(s) of the SQL table.
     * @return vector of primary keys
     */
    virtual std::set<std::string> keys() const = 0;
    
    /**
     * @brief Return true if the primary key is of type INTEGER and should have a unique value automatically chosen when inserting, false otherwise.
     * @return true if the key should be auto generated, false otherwise
     */
    virtual bool isAutoGeneratedKey() const = 0;
    
    /**
     * Returns a map representation of this object where for each member variable there is a key value pair where
     * the key is the name of the member variable and the value is the value of the member variable.
     * @return A map representation of this object.
     */
    virtual std::map<std::string, std::any> toMap() const = 0;
    
    /**
     * Returns a pointer to a new object with member variables initialized according to mMap.
     * @param mMap A map representation of the object, as created by a call to toMap().
     * @return Pointer to the new model.
     */
    virtual Model * fromMap(std::map<std::string, std::any> mMap) const = 0;
};

#endif /* Model_hpp */
