//
//  OrderMaster.hpp
//

#ifndef OrderMaster_hpp
#define OrderMaster_hpp

#include <map>
#include <string>

#include "Model.hpp"

/**
 * @brief Class representing a row of the OrderMaster table.
 *
 * @author Julian Koksal
 * @date 2022-11-07
 */
class OrderMaster : public Model
{
public:
    /**
     * @brief Constructor.
     *
     * Creates a OrderMaster object initialized with the given values.
     *
     * @param orderNumber The order number (primary key).
     * @param orderedBy Name of the customer of who placed the order.
     * @param orderDate The date and time of the order.
     * @param status Status of the order, can be "cart", "ordered", or "complete".
     * @param sessionID Session ID of the user, used for orders in the cart
     */
    OrderMaster(int orderNumber = 0, std::string orderedBy = "", std::string orderDate = "", std::string status = "", std::string sessionID = "");

    /**
     * @brief Destructor.
     *
     * Does nothing.
     */
    ~OrderMaster();

    /**
     * @brief Gets the order number.
     *
     * @return orderNumber
     */
    int getOrderNumber();

    /**
     * @brief Gets orderedBy.
     *
     * @return orderedBy
     */
    std::string getOrderedBy();

    /**
     * @brief Gets the order date.
     *
     * @return orderDate
     */
    std::string getOrderDate();

    /**
     * @brief Gets the session ID.
     * @return sessionID
     */
    std::string getSessionID();

    /**
     * @brief Get the status of the order.
     *
     * @return std::string
     */
    std::string getStatus();

    /**
     * @brief Sets orderedBy.
     *
     * @param val The new value.
     */
    void setOrderedBy(std::string val);

    /**
     * @brief Sets orderDate.
     *
     * @param val The new value.
     */
    void setOrderDate(std::string val);

    /**
     * @brief Sets the status of the order.
     * @param val The new value.
     */
    void setStatus(std::string val);
    
    /**
     * @brief Sets the session ID.
     * @param val The new value.
     */
    void setSessionID(std::string val);
    
private:
    /**
     * @brief The order number (primary key).
     */
    int orderNumber;
    
    /**
     * @brief Name of the customer of who placed the order.
     */
    std::string orderedBy;
    
    /**
     * @brief The date and time of the order.
     */
    std::string orderDate;
    
    
    /**
     * @brief The status of the Order, can be "cart", "ordered", or "complete"
     */
    std::string status;

    /**
     * The session ID of the user.
     */
    std::string sessionID;

    virtual std::string tableName() const override;
    virtual std::vector<std::string> columns() const override;
    virtual std::set<std::string> keys() const override;
    virtual bool isAutoGeneratedKey() const override;
    virtual std::map<std::string, std::any> toMap() const override;
    virtual Model* fromMap(std::map<std::string, std::any> mMap) const override;
};

#endif /* OrderMaster_hpp */
