//
// Created by Sharon Nikritin on 2022-11-07.
//

#include "OrderDetail.hpp"

OrderDetail ::OrderDetail(int orderDetailID, int orderNumber, std::string menuItemName, int quantity) {
    this -> orderDetailID = orderDetailID;
    this -> orderNumber = orderNumber;
    this -> menuItemName = menuItemName;
    this -> quantity = quantity;
}

OrderDetail :: ~OrderDetail() {
    
}

int OrderDetail ::getOrderDetailID() {
    return orderDetailID;
}

int OrderDetail ::getOrderNumber() {
    return orderNumber;
}

std::string OrderDetail ::getMenuItemName() {
    return menuItemName;
}

int OrderDetail ::getQuantity() {
    return quantity;
}

void OrderDetail ::setOrderNumber(int orderNumber) {
    this -> orderNumber = orderNumber;
}

void OrderDetail ::setMenuItemName(std::string menuItemName) {
    this -> menuItemName = menuItemName;
}

void OrderDetail ::setQuantity(int quantity) {
    this -> quantity = quantity;
}


std::string OrderDetail::tableName() const
{
    return "OrderDetail";
}

std::vector<std::string> OrderDetail::columns() const
{
    return { "orderDetailID", "orderNumber", "menuItemName", "quantity" };
}

std::set<std::string> OrderDetail::keys() const
{
    return { columns()[0] };
}

bool OrderDetail::isAutoGeneratedKey() const
{
    return true;
}

std::map<std::string, std::any> OrderDetail:: toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap[columns()[0]] = orderDetailID;
    mMap[columns()[1]] = orderNumber;
    mMap[columns()[2]] = menuItemName;
    mMap[columns()[3]] = quantity;

    return mMap;
}

Model * OrderDetail::fromMap(std::map<std::string, std::any> mMap) const
{
    int mOrderDetailID = std::any_cast<int>(mMap[columns()[0]]);
    int mOrderNumber = std::any_cast<int>(mMap[columns()[1]]);
    std::string mName = std::any_cast<std::string>(mMap[columns()[2]]);
    int mQuantity = std::any_cast<int>(mMap[columns()[3]]);
    OrderDetail *model = new OrderDetail(mOrderDetailID, mOrderNumber, mName, mQuantity);

    return model;
}
