//
//  vOrderDetail.cpp
//  group8
//
//  Created by Julian Koksal on 2022-11-08.
//

#include "vOrderDetail.hpp"

vOrderDetail::vOrderDetail(int orderDetailID, int orderNumber, std::string menuItemName, int quantity, double price, double total)
{
    this->tableName = "vOrderDetail";
    this->columns = { "orderDetailID", "orderNumber", "menuItemName", "quantity", "price", "total" };
    this->keys = { columns[0] };
    this->isAutoGeneratedKey = false;
    
    this->orderDetailID = orderDetailID;
    this->orderNumber = orderNumber;
    this->menuItemName = menuItemName;
    this->quantity = quantity;
    this->price = price;
    this->total = total;
}

vOrderDetail::~vOrderDetail()
{
    
}

std::map<std::string, std::any> vOrderDetail:: toMap() const
{
    std::map<std::string, std::any> mMap;
    mMap[columns[0]] = orderDetailID;
    mMap[columns[1]] = orderNumber;
    mMap[columns[2]] = menuItemName;
    mMap[columns[3]] = quantity;
    mMap[columns[4]] = price;
    mMap[columns[5]] = total;

    return mMap;
}

Model * vOrderDetail::fromMap(std::map<std::string, std::any> mMap) const
{
    int mOrderDetailID = std::any_cast<int>(mMap[columns[0]]);
    int mOrderNumber = std::any_cast<int>(mMap[columns[1]]);
    std::string mName = std::any_cast<std::string>(mMap[columns[2]]);
    int mQuantity = std::any_cast<int>(mMap[columns[3]]);
    double mPrice = std::any_cast<double>(mMap[columns[4]]);
    double mTotal = std::any_cast<double>(mMap[columns[5]]);
    vOrderDetail *model = new vOrderDetail(mOrderDetailID, mOrderNumber, mName, mQuantity, mPrice, mTotal);

    return model;
}

int vOrderDetail::getOrderDetailID() {
    return orderDetailID;
}

int vOrderDetail::getOrderNumber() {
    return orderNumber;
}

std::string vOrderDetail::getMenuItemName() {
    return menuItemName;
}

int vOrderDetail::getQuantity() {
    return quantity;
}

double vOrderDetail::getPrice() {
    return price;
}

double vOrderDetail::getTotal()
{
    return total;
}
