//
//  vOrderSales.hpp
//

#ifndef vOrderSales_hpp
#define vOrderSales_hpp

#include <string>
#include <map>

#include "Model.hpp"

/**
 * @brief Represents the vOrderSales view in the database.
 *
 * @author Julian Koksal
 * @date 2022-11-19
 */
class vOrderSales : public Model
{
public:
    vOrderSales(std::string salesDate = "", std::string menuItemName = "", int totalQuantity = 0, double totalRevenue = 0, bool isAllMenuItems = 0);

    ~vOrderSales();
    
    std::string getSalesDate();
    
    std::string getMenuItemName();
    
    int getTotalQuantity();
    
    double getTotalRevenue();
    
    bool getIsAllMenuItems();

private:
    std::string salesDate;
    
    std::string menuItemName;
    
    int totalQuantity;
    
    double totalRevenue;
    
    bool isAllMenuItems;
    
    virtual std::string tableName() const override;
    virtual std::vector<std::string> columns() const override;
    virtual std::set<std::string> keys() const override;
    virtual bool isAutoGeneratedKey() const override;
    virtual std::map<std::string, std::any> toMap() const override;
    virtual Model * fromMap(std::map<std::string, std::any> mMap) const override;
};


#endif /* vOrderSales_hpp */
